### ISSUE TITLE
JSON dump fails

### ISSUE THREAD

**Issue by reddigari** [FNNDSC/pfdicom_tagSub#2]
Running this program with the `--json` flag throws a serialization-related error (but only if tag substitution was actually performed). The culprit (see stack trace) appears to be a `pydicom.DataElement`, so I'm guessing something returned in `pfdicom`'s `ret_dump()` is no longer serializable. I didn't dig into it, though. 

```
Traceback (most recent call last):
  File "/home/brainspec/anaconda3/envs/chris/bin/pfdicom_tagSub", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/brainspec/Tools/fnndsc/pfdicom_tagSub/bin/pfdicom_tagSub", line 404, in <module>
    d_pfdicom_tagSub = pf_dicom_tagSub.run(timerStart = True)
  File "/home/brainspec/Tools/fnndsc/pfdicom_tagSub/bin/../pfdicom_tagSub/pfdicom_tagSub.py", line 432, in run
    self.ret_dump(d_ret, **kwargs)
  File "/home/brainspec/anaconda3/envs/chris/lib/python3.8/site-packages/pfdicom/pfdicom.py", line 492, in ret_dump
    json.dumps(   
  File "/home/brainspec/anaconda3/envs/chris/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/brainspec/anaconda3/envs/chris/lib/python3.8/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/home/brainspec/anaconda3/envs/chris/lib/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/home/brainspec/anaconda3/envs/chris/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/home/brainspec/anaconda3/envs/chris/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/home/brainspec/anaconda3/envs/chris/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/home/brainspec/anaconda3/envs/chris/lib/python3.8/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/home/brainspec/anaconda3/envs/chris/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/home/brainspec/anaconda3/envs/chris/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/home/brainspec/anaconda3/envs/chris/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataElement is not JSON serializable
```

**Comment by Sandip117** [comment]
@reddigari I am unable to replicate this issue. Can you provide some additional info?
